version: "3.5"
services:
  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: rs_configured_mongo
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    networks:
      - app
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: rs_configured_mongo
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    networks:
      - app
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: rs_configured_mongo
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    networks:
      - app
networks:
  app:
    name: "app"