swagger: "2.0"
info:
  description: "JWT authorization service on Golang"
  version: "1.0.0"
  title: "Auth-Go"
schemes:
- http
paths:
  /login:
    get:
      tags:
        - Log In
      parameters:
        - name: client_id
          in: query
          type: string
          format: uuid
      responses:
        200:
          description: Give new token pair
          schema:
            $ref: '#/definitions/token_pair'
        400:
          description: Missing userid
          schema:
            $ref: '#/definitions/error'
        500:
          description: Server error
          schema:
            $ref: '#/definitions/error'
  /refresh:
    post:
      tags:
        - Refresh
      parameters:
        - name: token
          required: true
          in: body
          schema: 
            $ref: '#/definitions/refresh_token'
      responses:
        200:
          description: Give new token pair
          schema:
            $ref: '#/definitions/token_pair'
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/error'
        500:
          description: Server error
          schema:
            $ref: '#/definitions/error'
      security:
        - auth_go: []
  /logout:
    post:
      tags:
        - Log Out
      description: Logout user from one device
      parameters:
        - name: token
          required: true
          in: body
          schema: 
            $ref: '#/definitions/refresh_token'
      responses:
        200:
          description: Success logout
        400:
          description: Bad request
          schema:
            $ref: '#/definitions/error'
        500:
          description: Server error
          schema:
            $ref: '#/definitions/error'
      security:
        - auth_go: []
  /logout/all:
    get:
      tags:
        - Log Out
      description: Logout user from all devices
      responses:
        200:
          description: Success logout
        500:
          description: Server error
          schema:
            $ref: '#/definitions/error'
      security:
        - auth_go: []
        
        
securityDefinitions:
  auth_go:
    type: oauth2
    flow: implicit
    authorizationUrl: https://hidden-dawn-44552.herokuapp.com/login
    
    
definitions:
  token_pair:
    type: object
    properties:
      refresh_token:
        type: string
      access_token:
        type: string
    example: 
      refresh_token: "This should be JWT token"
      access_token: "This should be JWT token"
  refresh_token:
    type: object
    required:
      - refresh_token
    properties:
      refresh_token:
        type: "string"
    example: 
      refresh_token: "this shuld be JWT token"
  error:
    type: string
    example: "Error description"